apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: spring-boot-greeter
 namespace: openshift-gitops
spec:
 destination:
   namespace: icon
   server: https://kubernetes.default.svc
 project: default
 source:
   path: gitops/spring-boot-greeter
   repoURL: https://github.com/djeremiah/gitops-demo.git
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
